POST http://localhost:3000/login
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "username" : "marko-2",
  "password" : "asdfsadasd"
}

> {%
    client.global.set("token", response.headers.valueOf('Set-Cookie'));
%}

###

