version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 127.0.0.12:3000:3000
      - 127.0.0.12:9229:9229
    depends_on:
      - postgres
    links:
      - postgres:postgres
    command: npm run start:dev
    volumes:
      # development folders
      - ./src:/server/src
      - ./test:/server/test

  postgres:
    # Stable 11 - Final release November 9, 2023
    image: postgres:11.1-alpine
    restart: always
    ports:
      - 127.0.0.12:5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    # todo - make a stable database with sample data for repeatable testing
    #  - ./docker/postgres/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB


volumes:
  postgres: