# development docker-compose

version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - TYPEORM_HOST=postgres
      - TYPEORM_PORT=5432
      - TYPEORM_DATABASE=povioliked
      - TYPEORM_USERNAME=povioliked
      - TYPEORM_PASSWORD=poviolikedps
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_MIGRATIONS_RUN=true
      - TYPEORM_ENTITIES=src/**/*.entity.ts
      - SECRET_KEY=e9c87gnt4hmf8gwy9qg8gwberoi
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - postgres
    links:
      - postgres:postgres
    #command: npm run start:dev
    # debugger
    command: npm run start:debug
    volumes:
      # development folders
      - ./src:/server/src:ro
      - ./test:/server/test:ro
    networks:
      - povio-liked

  postgres:
    # Stable 11 - Final release November 9, 2023
    image: postgres:11.1-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    # todo - make a stable database with sample data for repeatable testing
      - ./seed/postgres/:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_PASSWORD=poviolikedps
      - POSTGRES_USER=povioliked
      - POSTGRES_DB=povioliked
    networks:
      - povio-liked

volumes:
  postgres:

networks:
  povio-liked:
    external: true


